### ISSUE TITLE
Connection string is invalid

### ISSUE THREAD

**Issue by arpitmishra-eaton** [Azure/AppConfiguration-Sync#29]
I have submitted a secret using function app publish profile in repository. 

name for secret is AZURE_FUNCTIONAPP_PUBLISH_PROFILE
and value is data given in Publish profile.

Here is the script: Please help

on: 
  #workflow_dispatch:
  push: 
    branches: 
      - developer 
    paths: 
      - 'appsettings.json' 
 
jobs: 
  syncconfig: 
    runs-on: ubuntu-latest 
    steps: 
      # checkout done so that files in the repo can be read by the sync 
      - uses: actions/checkout@v1 
      - uses: azure/appconfiguration-sync@v1 
        with: 
          configurationFile: 'appsettings.json' 
          format: 'json' 
          # Replace <ConnectionString> with the name of the secret in your                        
          # repository 
          #publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          connectionString: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          separator: ':'

**Comment by zhenlan** [comment]
@arpitmishra-eaton you should obtain the connection string from your Azure App Configuration store. From the Azure Portal, navigate to your App Configuration store -> `Access keys` -> copy one of `Read-write keys`.

**Comment by arpitmishra-eaton** [comment]
with this, Can i update app setting of function app, please?

**Comment by zhenlan** [comment]
This GitHub action is to update settings in Azure App Configuration. It's not to update settings in Function App. You can, however, load settings in Azure App Configuration from your Function App.

https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-azure-functions-csharp

**Comment by arpitmishra-eaton** [comment]
oh, Thanks! is there a way we can update app setting of function app using Github Action or the pipeline, please

**Comment by zhenlan** [comment]
That's a question you may like to reach out to the Azure Functions team https://github.com/Azure/azure-functions-host.

**Comment by arpitmishra-eaton** [comment]
Thanks Much @zhenlan
