### ISSUE TITLE
Unable to authenticate - 401 Unauthorized

### ISSUE THREAD

**Issue by myakimov** [Azure/AppConfiguration-Sync#31]
Using the action with its current release from February, seems to result in HTTP 401 returned from the Azure App Configuration services. 

I forked the repository and updated the @azure/app-configuration to latest 1.3.1 which seems to have resolved the issue. 

Would it be possible to update the action to the latest dependencies used ? 

Thanks in advance!

**Comment by jonms90** [comment]
Would be nice to solve this to be able to use this action!

**Comment by ChristineWanjau** [comment]
Hello @myakimov thank you for opening up this issue. We are deprecating this action. We recommend using Azure CLI action instead. Follow [this guide](https://learn.microsoft.com/en-us/azure/azure-app-configuration/push-kv-github-action) on how to set it up in your github actions.
