### ISSUE TITLE
Use Azure AD to authenticate to Azure App Configuration

### ISSUE THREAD

**Issue by kamil-kamola-mir** [Azure/AppConfiguration-Sync#46]
Hello,

for more secured scenarios where Access Keys are disabled in Azure App Configuration instance there should be option to authenticate with Azure AD (for example Managed Identities) and not only with Connection String.

Greetings.

**Comment by zhenlan** [comment]
@et13 is this technically doable in GitHub action?

**Comment by ChristineWanjau** [comment]
Hello @kamil-kamola-mir thank you for opening up this issue. We are deprecating this action. We recommend using Azure CLI action instead and Azure/Login to use to Azure AD to authenticate to Azure App Configuration. Follow [this guide](https://learn.microsoft.com/en-us/azure/azure-app-configuration/push-kv-github-action) on how to set it up in your github actions.
