### ISSUE TITLE
Support for the KVSet Schema

### ISSUE THREAD

**Issue by nnellanspdl** [Azure/AppConfiguration-Sync#51]
Is this Action abandoned?  It hasn't seen an updated in 2 years.

The equivalent Azure DevOps Task has been updated more frequently and supports more features.  Namely, it would be nice if this Action supported the [KVSet](https://learn.microsoft.com/en-us/azure/azure-app-configuration/concept-config-file#file-content-profile-kvset) schema for config files.

**Comment by zhenlan** [comment]
@nnellanspdl thanks for querying. It's supported, but the team priority has (always) been adjusted based on usage and customer demands.

**Comment by nnellanspdl** [comment]
> @nnellanspdl thanks for querying. It's supported, but the team priority has (always) been adjusted based on usage and customer demands.

Thanks!  Is it possible to update the action to support the KVSet schema?  The Azure DevOps Task has already been updated to support this, but we would prefer to use GitHub Workflows.

**Comment by zhenlan** [comment]
Thanks for the feedback, @nnellanspdl. We will try to get to this in the next 3~6 months.

**Comment by ChristineWanjau** [comment]
Hello @nnellanspdl  thank you for opening up this issue. We are deprecating this action. We recommend using Azure CLI action instead. Azure CLI has support for the KVSet schema and supports more features than this action had. Follow [this guide](https://learn.microsoft.com/en-us/azure/azure-app-configuration/push-kv-github-action) on how to set it up in your github actions.
