### ISSUE TITLE
No configuration file found

### ISSUE THREAD

**Issue by chandan-g-bhagat** [Azure/AppConfiguration-Sync#9]
Hi there, I was using this but I encountered the issue 
![image](https://user-images.githubusercontent.com/6848264/76976904-b141ab00-695c-11ea-9743-dfcb0371b17f.png)
where as my github yml workflow part is
![image](https://user-images.githubusercontent.com/6848264/76975638-f06efc80-695a-11ea-98d5-fa6b91ae7528.png)
Also my file structure is
![image](https://user-images.githubusercontent.com/6848264/76975731-1399ac00-695b-11ea-9553-1bab5868d5d1.png)

Any issues or anything I am missing?

**Comment by et13** [comment]
Hi @chandan-g-bhagat, can you try adding a step to use `actions/checkout` before `Azure App Configuration Sync`?

`- uses: actions/checkout@v1 `

What that does is check out your repository on the machine running the workflow so that subsequent steps can access repository contents.

**Comment by chandan-g-bhagat** [comment]
That worked. But I was wondering if there is anyway we can post data to azure app configuration

**Comment by et13** [comment]
Hi @chandan-g-bhagat, I'm not sure if this is what you're looking for, but we have documentation [here](https://github.com/Azure/AppConfiguration/blob/master/README.md) that contains information about Azure App Configuration API/SDKs. If not, could you elaborate more about what you're trying to achieve?

**Comment by chandan-g-bhagat** [comment]
Thanks @et13 I viewed this document and my problem are resolved. Closing this issue.
